### ISSUE TITLE
Newest version doesn't work in eu-central-1

### ISSUE THREAD

**Issue by chopmo** [americanhonors-cookbooks/aws-sdk#1]
The `eu-central-1` (Frankfurt) region requires Signature Version 4 for EC2 connections, which is not supported by version 1.42.0 of the gem. Confusingly, querying RDS objects works fine. 

The details are here: https://forums.aws.amazon.com/message.jspa?messageID=578908

I suppose this simply requires bumping the version and re-releasing?

**Comment by ghost** [comment]
(Copied from my response to #2)

Sorry for the delay, I think we are actually going to deprecate this cookbook in favor of [v2.6.0](https://github.com/opscode-cookbooks/aws/releases/tag/v2.6.0) of the [Opscode aws cookbook](https://github.com/opscode-cookbooks/aws), now that it accomplishes the same thing as this ~~gem~~ cookbook and thensome. If you would still like this cookbook to be upgraded to the latest dependencies for apt and build-essential, I would be happy to accept a pull request.
