### ISSUE TITLE
Updates for apt and build-essential dependencies

### ISSUE THREAD

**Issue by davidski** [americanhonors-cookbooks/aws-sdk#2]
Any chance the `apt` and `build-essential` dependencies can be updated to more current versions? I'm testing this cookbook out in a somewhat complicated stack and I'm hitting version conflicts with other recipes that have newer dependencies. Specifically looking at the 2.6 train for `apt` and the 2.1 train for `build-essential`.

Thanks!

**Comment by ghost** [comment]
Thanks for the heads up on the dependencies here! I think I should be able to release a new version of this with updated dependencies by the end of tomorrow.

## 

Tony Burns
Tech Ops Lead

Quad Learning, Inc. | American Honors
1150 17th St. NW, Suite 310, Washington, D.C. 20036
mobile 608.799.2000
office 202.525.1078
email Tony.Burns@AmericanHonors.org
website AmericanHonors.org

**Comment by ghost** [comment]
Sorry for the delay, I think we are actually going to deprecate this cookbook in favor of [v2.6.0](https://github.com/opscode-cookbooks/aws/releases/tag/v2.6.0) of the [Opscode aws cookbook](https://github.com/opscode-cookbooks/aws), now that it accomplishes the same thing as this ~~gem~~ cookbook and thensome. If you would still like this cookbook to be upgraded to the latest dependencies for apt and build-essential, I would be happy to accept a pull request.
